#!/usr/bin/env escript

%% argparse example, without cli behaviour used
%% how to try:
%%  ERL_FLAGS="-pa ../../../_build/default/lib/argparse/ebin" ./erm -rf dir

main(Args) ->
    io:format("~ts~n", [argparse:help(cli())]).

%% parser specification
cli() ->
    #{arguments => [
        #{name => force, short => $f, type => boolean, default => false},
        #{name => recursive, short => $r, type => boolean, default => false},
        #{name => dir}
    ]}.
