name: Build, Test, Dialyze

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - 'master'

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['21.2', '22', '23']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          rebar3-version: '3.15.1'
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do edoc,ct
      - shell: bash
        name: Dialyzer
        run: rebar3 dialyzer
